# Generated by Django 5.2.12 on 2026-08-31 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trust', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('support_type', models.CharField(choices=[('annadhanam', 'Annadhanam (Daily Meal Sponsorship)'), ('elder_care', 'Elder Care & Medical Support'), ('scholarship', 'Educational Scholarship Support'), ('volunteer', 'Volunteer & Service'), ('general', 'General Donation / Support')], max_length=30)),
                ('contribution_details', models.CharField(blank=True, help_text='e.g. Birthday Annadhanam, Rs 5000/month', max_length=150)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Trust enquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
