# Generated by Django 5.2.12 on 2026-08-31 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('event_type', models.CharField(choices=[('wedding', 'Wedding Ceremony & Reception'), ('corporate', 'Corporate Conference / Product Launch'), ('social', 'Birthday / Family Gathering'), ('vendor', 'Vendor Sourcing (Catering / Decor / Photo)'), ('day_of', 'Day-of Event Coordination')], max_length=30)),
                ('event_date', models.CharField(blank=True, help_text='Proposed date or month', max_length=50)),
                ('expected_guests', models.CharField(blank=True, help_text='e.g. 500 guests', max_length=50)),
                ('preferred_location', models.CharField(blank=True, help_text='e.g. ECR Beach Resort, Hotel in Guindy', max_length=150)),
                ('special_requirements', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Event enquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
