# Generated by Django 5.2.17 on 2026-08-31 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventenquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(help_text='e.g. ECR Beach Resort, Guindy Hotel', max_length=150)),
                ('category', models.CharField(choices=[('wedding', 'Weddings & Receptions'), ('corporate', 'Corporate & Conferences'), ('social', 'Social Galas & Parties'), ('decor', 'Custom Decor & Floral')], default='wedding', max_length=30)),
                ('guest_capacity', models.CharField(blank=True, help_text='e.g. 600 Guests', max_length=50)),
                ('completion_year', models.CharField(default='2024', max_length=10)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Event portfolio items',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
