# Generated by Django 5.2.12 on 2026-08-31 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventType',
        ),
        migrations.DeleteModel(
            name='LegalService',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='TrustProgram',
        ),
    ]
