# Generated by Django 5.0.14 on 2026-09-03 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_eventtype_delete_legalservice_delete_service_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessDivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('short_description', models.TextField(help_text='Short description shown on cards/homepage')),
                ('full_description', models.TextField(blank=True, help_text='In-depth about description on dedicated page')),
                ('division_type', models.CharField(choices=[('business', 'Commercial Business'), ('foundation_trust', 'Foundation & Social Initiative')], default='business', max_length=30)),
                ('icon_name', models.CharField(blank=True, help_text='Lucide/SVG icon identifier', max_length=50)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='divisions/')),
                ('static_image_path', models.CharField(blank=True, help_text='Fallback static image path', max_length=255)),
                ('accent_color', models.CharField(default='#7C3B29', max_length=20)),
                ('target_url', models.CharField(blank=True, help_text='Target URL if custom routed', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Business Division',
                'verbose_name_plural': 'Business Divisions',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MediaArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('category', models.CharField(default='Press Release', max_length=80)),
                ('summary', models.TextField()),
                ('content', models.TextField(blank=True)),
                ('publish_date', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media_articles/')),
                ('static_image_path', models.CharField(blank=True, max_length=255)),
                ('featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-publish_date', 'order'],
            },
        ),
        migrations.AddField(
            model_name='contactenquiry',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news/'),
        ),
        migrations.AlterField(
            model_name='contactenquiry',
            name='service',
            field=models.CharField(choices=[('general', 'General Enquiry'), ('foundation', 'Bairava Foundation'), ('finance', 'Bairava Finance'), ('construction', 'Bairava Construction & Promoters'), ('cloud_kitchen', 'Bairava Cloud Kitchen'), ('sports_club', 'Bairava Sports Club'), ('event_management', 'Bairava Event Management'), ('aadukalam', 'Bairava Aadukalam'), ('trust', 'Bairava Trust'), ('media', 'Bairava Media'), ('legal', 'Legal Consultation')], default='general', max_length=30),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='category',
            field=models.CharField(choices=[('trust', 'Trust activity'), ('community', 'Community'), ('construction', 'Construction'), ('legal', 'Legal'), ('events', 'Events'), ('sports', 'Sports & Youth'), ('media', 'Media & Press'), ('general', 'Group Update')], default='trust', max_length=20),
        ),
        migrations.AlterField(
            model_name='stat',
            name='label',
            field=models.CharField(help_text="e.g. 'Years of Excellence'", max_length=100),
        ),
        migrations.CreateModel(
            name='DivisionEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('requirement_type', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to='core.businessdivision')),
            ],
            options={
                'verbose_name': 'Division Enquiry',
                'verbose_name_plural': 'Division Enquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DivisionGalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='division_gallery/')),
                ('static_image_path', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_items', to='core.businessdivision')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DivisionOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('badge', models.CharField(blank=True, help_text="e.g. 'Popular', 'Organic', 'Certified'", max_length=60)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='core.businessdivision')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
    ]
