# Generated by Django 5.0.14 on 2026-09-05 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_businessdivision_mediaarticle_contactenquiry_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactenquiry',
            name='service',
            field=models.CharField(choices=[('general', 'General Enquiry'), ('future_plan', 'Future Initiatives & Partnerships'), ('finance', 'Bairava Finance'), ('construction', 'Bairava Construction & Land Promoters'), ('cloud_kitchen', 'Bairava Cloud Kitchen'), ('sports_club', 'Bairava Sports Club'), ('event_management', 'Bairava Event Management'), ('aadukalam', 'Bairava Aadukalam'), ('media', 'Bairava Media'), ('water', 'Bairava Water'), ('jewellery', 'Bairava Jewellery'), ('foundation', 'Bairava Foundation'), ('trust', 'Bairava Trust'), ('legal', 'Legal Consultation')], default='general', max_length=30),
        ),
    ]
