# Generated by Django 5.0.14 on 2026-09-06 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_contactenquiry_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactenquiry',
            name='service',
            field=models.CharField(choices=[('general', 'General Enquiry'), ('foundation', 'Bairava Foundation'), ('finance', 'Bairava Finance'), ('construction', 'Bairava Construction & Promoters'), ('cloud_kitchen', 'Bairava Cloud Kitchen'), ('sports_club', 'Bairava Sports Club'), ('event_management', 'Bairava Event Management'), ('aadukalam', 'Bairava Aadukalam'), ('trust', 'Bairava Trust'), ('media', 'Bairava Media'), ('legal', 'Legal Consultation')], default='general', max_length=30),
        ),
    ]
