# Generated by Django 5.0.14 on 2026-09-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_businessdivision_division_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactenquiry',
            name='service',
            field=models.CharField(choices=[('general', 'GENERAL ENQUIRY'), ('foundation', 'BAIRAVA FOUNDATION'), ('finance', 'BAIRAVA FINANCE'), ('construction', 'BAIRAVA CONSTRUCTION & LAND PROMOTERS'), ('cloud_kitchen', 'BAIRAVA CLOUD KITCHEN'), ('sports_club', 'BAIRAVA SPORTS CLUB'), ('event_management', 'BAIRAVA EVENT MANAGEMENT'), ('aadukalam', 'BAIRAVA AADUKALAM'), ('trust', 'BAIRAVA TRUST'), ('media', 'BAIRAVA MEDIA'), ('association', 'BAIRAVA LAW ASSOCIATES'), ('law_associates', 'BAIRAVA LAW ASSOCIATES'), ('legal', 'LEGAL CONSULTATION')], default='general', max_length=30),
        ),
    ]
