# Generated by Django 5.0.14 on 2026-09-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_contactenquiry_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactenquiry',
            name='service',
            field=models.CharField(choices=[('general', 'GENERAL ENQUIRY'), ('foundation', 'BAIRAVA FOUNDATION'), ('finance', 'BAIRAVA FINANCE'), ('construction', 'BAIRAVA CONSTRUCTION & LAND PROMOTERS'), ('cloud_kitchen', 'BAIRAVA & JK KITCHEN'), ('sports_club', 'BAIRAVA SPORTS CLUB'), ('event_management', 'BAIRAVA EVENT MANAGEMENT'), ('aadukalam', 'BAIRAVA AADUKALAM'), ('trust', 'BAIRAVA TRUST'), ('media', 'BAIRAVA MEDIA'), ('law_associates', 'BAIRAVA LAW ASSOCIATES')], default='general', max_length=30),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='category',
            field=models.CharField(choices=[('trust', 'TRUST ACTIVITY'), ('community', 'COMMUNITY'), ('construction', 'CONSTRUCTION'), ('events', 'EVENTS'), ('sports', 'SPORTS & YOUTH'), ('media', 'MEDIA & PRESS'), ('general', 'GROUP UPDATE')], default='trust', max_length=20),
        ),
    ]
