# Generated by Django 5.2.12 on 2026-08-31 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('law_associates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('issue_type', models.CharField(choices=[('notice', 'Legal Notice Consultation'), ('property', 'Property Verification & Due Diligence'), ('recovery', 'Money Recovery Case'), ('criminal', 'Criminal Defense & Bail'), ('protection', 'Harassment / Recovery Agent Protection'), ('opinion', 'General Legal Opinion')], max_length=30)),
                ('urgency', models.CharField(choices=[('immediate', 'Immediate / Court Notice Received'), ('urgent', 'Within 3 Days'), ('general', 'General Advice')], default='urgent', max_length=20)),
                ('brief_details', models.TextField(help_text='Brief description of the legal matter')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Legal enquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
