# Generated by Django 5.2.17 on 2026-08-31 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('law_associates', '0002_legalenquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalPracticeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('notice', 'Legal Notices & Replies'), ('property', 'Property Due Diligence & Titles'), ('recovery', 'Money Recovery & Cheque Bounce'), ('criminal', 'Criminal Defense & Bail'), ('protection', 'Recovery Agent Protection')], default='notice', max_length=30)),
                ('turnaround_time', models.CharField(blank=True, help_text='e.g. 24 - 48 Hour Opinion', max_length=100)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Legal practice details',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
