# Generated by Django 5.2.12 on 2026-08-31 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(help_text='e.g. Anna Nagar, Chennai', max_length=150)),
                ('category', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('villas', 'Villas & Bungalows'), ('interiors', 'Interiors & Renovations')], default='residential', max_length=30)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('ongoing', 'Ongoing'), ('upcoming', 'Upcoming')], default='completed', max_length=20)),
                ('description', models.TextField()),
                ('completion_year', models.CharField(default='2024', max_length=10)),
                ('built_up_area', models.CharField(blank=True, help_text='e.g. 4,500 sq.ft', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
