# Generated by Django 5.2.12 on 2026-08-31 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0002_constructionproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('project_type', models.CharField(choices=[('residential', 'Residential House'), ('commercial', 'Commercial Complex / Office'), ('villa', 'Independent Villa / Bungalow'), ('flat', 'Flat / Apartment Block'), ('interiors', 'Interiors & False Ceiling'), ('kitchen', 'Modular Kitchen')], max_length=30)),
                ('location', models.CharField(help_text='Site location in Chennai', max_length=150)),
                ('plot_area', models.CharField(blank=True, help_text='e.g. 2,400 sq.ft', max_length=50)),
                ('estimated_budget', models.CharField(blank=True, help_text='e.g. 50 Lakhs - 1 Crore', max_length=50)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Construction enquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
