# Generated by Django 5.0.14 on 2026-09-07 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0003_constructionenquiry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='constructionproject',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='constructionproject',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
